version: "3"
services:
  web:
    stdin_open: true
    tty: true
    container_name: web_container
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    links:
      - db
      - redis
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    container_name: db_container
    volumes:
      - database:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379

  celery:
    restart: always
    build: .
    command: celery -A testservice worker -l info
    volumes:
      - ./:/src
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  database: