# Generated by Django 4.0.6 on 2022-07-24 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала обработки задачи')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения обработки задачи')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат обработки задачи')),
                ('csv_file_name', models.CharField(max_length=512, validators=[django.core.validators.RegexValidator('.+\\.csv$', message='Must be csv extension')], verbose_name='Название CSV файла')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done')], default='pending', max_length=20, verbose_name='Статус задачи')),
            ],
            options={
                'verbose_name': 'Задача обработки CSV файла',
                'verbose_name_plural': 'Задачи обработки CSV файлов',
            },
        ),
    ]
