# Generated by Django 4.0.6 on 2022-07-23 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания таски')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала обработки таски')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения обработки таски')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат обработки таски')),
                ('csv_file_name', models.CharField(max_length=512, validators=[django.core.validators.RegexValidator('.+\\.csv$', message='Must be csv extention')], verbose_name='Название CSV файла')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('I', 'In progress'), ('D', 'Done')], default='P', max_length=1, verbose_name='Статус таски')),
            ],
            options={
                'verbose_name': 'Таска обработки CSV файла',
                'verbose_name_plural': 'Таски обработки CSV файлов',
            },
        ),
    ]
